<div class="s-footer-sitemap">
    <div class="s-footer-sitemap__col">
        <ul class="s-footer-sitemap-list">
            <li><a href="/?p_no=1" target="_self">ZOZOTOWN</a></li>
            <li><a href="/shoes/?p_no=1" target="_self">ZOZOSHOES</a></li>
            <li><a href="/cosme/?p_no=1" target="_self">ZOZOCOSME</a></li>
            <li><a href="/zozogolf/?p_no=1" target="_self">ZOZOGOLF</a></li>
            <li><a href="/zozoused/" target="_self">ZOZOUSED</a></li>
            <li><a href="/zozovilla/?p_no=1" target="_self">ZOZOVILLA</a></li>
            <li><a href="/yourbrandproject/?p_no=1" target="_self">YOUR BRAND PROJECT</a></li>
            <li>
                <a class="s-footer-link" href="https://wear.jp/" target="_blank" rel="noopener noreferrer">
                    <div class="s-footer-link__label">
                        WEAR
                    </div>
                    <div class="s-footer-link__icon">
                        <span class="c-icon--external" aria-hidden="true"></span>
                    </div>
                </a>
            </li>
        </ul>
    </div>
    <div class="s-footer-sitemap__col">
        <ul class="s-footer-sitemap-list">
            <li><a href="/category/?p_no=1">カテゴリー一覧</a></li>
            <li><a href="/brand/?p_no=1">ブランド一覧</a></li>
            <li><a href="/shop/?p_no=1">公式ショップ一覧</a></li>
            <li><a href="/ranking/all-sales.html">ランキング一覧</a></li>
            <li><a href="/detail/?p_no=1">こだわり検索</a></li>
        </ul>
        <ul class="s-footer-sitemap-list">
            <li><a href="/coordinate/">コーディネート一覧</a></li>
            <li><a href="/topics/?p_no=1">ショップニュース一覧</a></li>
            <li><a href="/fashionnews/?p_no=1">ファッションまとめ一覧</a></li>
        </ul>
    </div>
    <div class="s-footer-sitemap__col">
        <ul class="s-footer-sitemap-list">
            <li><a href="/zozoglass/?p_no=1" target="_self">ZOZOGLASS</a></li>
            <li><a href="/zozomat/?p_no=1" target="_self">ZOZOMAT</a></li>
            <li><a href="/_card/?p_no=1" target="_self">ZOZOCARD</a></li>
            <li><a href="/multisize/?p_no=1" target="_self">マルチサイズ</a></li>
            <li><a href="/giftwrapping/?p_no=1" target="_self">ギフトラッピング</a></li>
            <li><a href="/_member/tradein/?p_no=1" target="_self">いつでも買い替え割</a></li>
            <li><a href="/_mail/?p_no=1" target="_self">メールマガジン購読</a></li>
        </ul>
    </div>
    <div class="s-footer-sitemap__col">
        <ul class="s-footer-sitemap-list">
            <li><a href="/_help/default.html?p_no=1" target="_self">ヘルプ</a></li>
            <li><a href="/welcome/default.html?p_no=1" target="_self">はじめての方へ</a></li>
            <li><a href="/sitemap.html" target="_self">サイトマップ</a></li>
        </ul>
    </div>
    <div class="s-footer-sitemap__col">
        <ul class="s-footer-sitemap-list">
            <li><a href="//itunes.apple.com/jp/app/zozotown/id404529222?mt=8&amp;p_no=1" target="_blank"
                    rel="noopener noreferrer">iPhoneアプリ</a></li>
            <li><a href="//play.google.com/store/apps/details?id=jp.zozo.android.town" target="_blank"
                    rel="noopener noreferrer">Androidアプリ</a></li>
            <li>
                <a class="s-footer-link" href="//twitter.com/zozojp" target="_blank" rel="noopener noreferrer">
                    <div class="s-footer-link__icon">
                        <span class="c-icon--twitter" aria-hidden="true"></span>
                    </div>
                    <div class="s-footer-link__label">
                        Twitter
                    </div>
                </a>
            </li>
            <li>
                <a class="s-footer-link" href="//www.facebook.com/zozotown" target="_blank" rel="noopener noreferrer">
                    <div class="s-footer-link__icon--large">
                        <span class="c-icon--facebook" aria-hidden="true"></span>
                    </div>
                    <div class="s-footer-link__label">
                        Facebook
                    </div>
                </a>
            </li>
            <li>
                <a class="s-footer-link" href="//instagram.com/zozotown/" target="_blank" rel="noopener noreferrer">
                    <div class="s-footer-link__icon">
                        <span class="c-icon--instagram" aria-hidden="true"></span>
                    </div>
                    <div class="s-footer-link__label">
                        Instagram
                    </div>
                </a>
            </li>
        </ul>
    </div>
</div>
