<div id="fCorporate" class="clearfix">
    <ul class="clearfix">
        <li>
            <a class="s-footer-link" href="https://corp.zozo.com/?p_no=1" target="_blank" rel="noopener noreferrer">
                <div class="s-footer-link__label">
                    コーポレートサイト
                </div>
                <div class="s-footer-link__icon">
                    <span class="c-icon--external" aria-hidden="true"></span>
                </div>
            </a>
        </li>
        <li>
            <a class="s-footer-link" href="https://corp.zozo.com/about/profile/" target="_blank"
                rel="noopener noreferrer">
                <div class="s-footer-link__label">
                    会社概要
                </div>
                <div class="s-footer-link__icon">
                    <span class="c-icon--external" aria-hidden="true"></span>
                </div>
            </a>
        </li>
        <li>
            <a class="s-footer-link" href="https://corp.zozo.com/ir/" target="_blank" rel="noopener noreferrer">
                <div class="s-footer-link__label">
                    IR情報
                </div>
                <div class="s-footer-link__icon">
                    <span class="c-icon--external" aria-hidden="true"></span>
                </div>
            </a>
        </li>
        <li>
            <a class="s-footer-link" href="https://corp.zozo.com/recruit/" target="_blank" rel="noopener noreferrer">
                <div class="s-footer-link__label">
                    採用情報
                </div>
                <div class="s-footer-link__icon">
                    <span class="c-icon--external" aria-hidden="true"></span>
                </div>
            </a>
        </li>
        <li><a href="/info/kiyaku.html?p_no=1">利用規約</a></li>
        <li><a href="/info/pp.html?p_no=1">プライバシーポリシー</a></li>
        <li><a href="/_newhelp/help_resort_torihikihou.html?p_no=1">特定商取引法に基づく表示・古物営業法に基づく表示</a></li>
    </ul>
    <div id="global-footer-copyright">© ZOZO, Inc.</div>
</div>
