<?php
    
    $products = $this->getProductCollection();
    if($this->getTyleList() == 'recen_view'){
        $products = $this->getRecenViewProduct();
        // echo count($products->load()) ;
        // echo count($products) ;
        // echo count($products->getData()) ;
        // echo count($products->load()->getData()) ;
    }
    $blockId = rand() . time();
    $themeHelper = $this->helper('Rikai\WidgetProduct\Helper\Data');
    $image = 'category_page_grid';
?>

<?php $category = $themeHelper->getCategory($block->getCategoryId());
    $categoryIdUrl = $themeHelper->getCategoryUrl($category);
?>
<i class="far fa-arrow-circle-left"></i>
<div class="block-product-list">
    <?php if($this->getData('title')): ?>
    <div class="block-title">
        <h2 class="title-custom"><?php echo $this->getData('title'); ?><?php if($block->getCategoryId() > 2 ): ?><a
                class="link-view-all" href="<?php echo $categoryIdUrl; ?>"><?php echo __('View all');?></a><?php endif ?></h2>
    </div>
    <?php if(count($products)>0): ?>
    <div id="myCarousel-<?php echo $blockId ?>" class="carousel slide" data-ride="carousel" data-interval="500000">
        <div class="block-content row carousel-inner">
            <?php $i = 0; foreach($products as $_product): $i++;
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $productModel = $objectManager->create('Magento\Catalog\Model\Product');
                $_product = $productModel->load($_product->getId());
                ?>
            <?php if($i == 1): ?>
            <div class="item active">
                <?php elseif($i%6 == 1): ?>
                <div class="item">
                    <?php endif ?>
                    <?php $_itemNameStripped = $block->stripTags($_product->getName(), null, true); ?>

                    <?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                    $size = $themeHelper->getImageSize();
                    $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                    ?>
                    <div class="product-content <?php if($i % 2 == 1): ?><?php endif ?>">
                        <div class="product-top">
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                                <img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>"
                                    class="img-responsive" />
                            </a>
                        </div>
                        <div class="product-details">
                            <h6 class="product-category-name">
                                <?php echo $themeHelper->getCategoryName($_product,$this->getData('title'),'') ?></h6>
                            <h6 class="product-name"><a
                                    href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a>
                            </h6>
                            <?php  echo $block->getProductPrice($_product) ?>

                        </div>
                    </div>
                    <?php if($i%6 == 0): ?>
                </div>
                <?php endif ?>
                <?php endforeach ?>
                <?php if($i%6 != 0): ?>
            </div>
            <?php endif ?>
        </div>
        <a class="carousel-control-prev left" href="#myCarousel-<?php echo $blockId ?>" role="button" data-slide="prev">
            <i class="fas fa-angle-double-left"></i>
        </a>
        <a class="carousel-control-next right" href="#myCarousel-<?php echo $blockId ?>" role="button"
            data-slide="next">
            <i class="fas fa-angle-double-right"></i>
        </a>
        <?php else: ?>
        <div class="carousel slide">
            <div class="block-content row carousel-inner">
                <div class="item active">
                    <?php echo __('No product to show'); ?>
                </div>
            </div>
            <?php endif ?>
            <?php endif ?>
        </div>
    </div>
