<?php 
    $products = $this->getProductCollection();
    $blockId = rand() . time();
    $themeHelper = $this->helper('Rikai\WidgetProduct\Helper\Data');
    $themeSettings = $themeHelper->getThemeSettings();
    $image = 'category_page_grid';
?>


<?php $category = $themeHelper->getCategory($block->getCategoryId());
    $categoryIdUrl = $category->getCategoryIdUrl(); 
?>
    
<div class="block-product-list">
<?php if($this->getData('title')): ?>
    <div class="block-title">
        <h2 class="title"><?php echo $this->getData('title'); ?></h2>
        <?php if($block->getCategoryId() != 2): ?><a class="link-view-all" href="<?php echo $categoryIdUrl; ?>">View all</a><?php endif ?>
    </div>
    <?php if(count($products)>0): ?>
        <div class="block-content row">
            <?php $i = 0; foreach($products as $_product): $i++;
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $productModel = $objectManager->create('Magento\Catalog\Model\Product');
                $_product = $productModel->load($_product->getId()); 
            ?>
                <?php $_itemNameStripped = $block->stripTags($_product->getName(), null, true); ?>

                <?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
				$size = $themeHelper->getImageSize();
				$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();  
                ?>
                <div class="product-content <?php if($i % 2 == 1): ?><?php endif ?>">
						<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
								<img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive"/>
							</a>
						</div>
						<div class="product-details">
                            <h6 class="product-category-name"><?php echo $themeHelper->getCategoryName($_product,$this->getData('title'),'') ?></h6>
							<h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a></h6>
							<?php  echo $block->getProductPrice($_product) ?>
                            
						</div>
					</div>
            <?php endforeach ?>
        </div>   
        <?php else: ?>
			<div class="alert alert-danger"><?php echo __('No product to show'); ?></div>
		<?php endif ?>
<?php endif ?>
</div>