<div id="footerNews" class="p-home-headline">
    <div class="c-section-header">
        <div class="c-section-header-primary">
            <h2 class="c-section-header-primary__heading">お知らせ</h2>
        </div>
    </div>
    <ul class="p-home-headline-list">

        <li class="p-home-headline-list__item">
            <p class="p-home-headline-list__title">不正ログインに対する注意喚起</p>
            <a href="https://zozo.jp/news/article/185/" class="p-home-headline-list__link">詳細はこちら</a>
        </li>

        <li class="p-home-headline-list__item">
            <p class="p-home-headline-list__title">iOS版アプリ一部サポート終了のお知らせ</p>
            <a href="https://zozo.jp/news/article/186/" class="p-home-headline-list__link">詳細はこちら</a>
        </li>

        <li class="p-home-headline-list__item">
            <p class="p-home-headline-list__title">【10/10更新】セールおよび天災による配送への影響について</p>
            <a href="https://zozo.jp/news/article/114/" class="p-home-headline-list__link">詳細はこちら</a>
        </li>

    </ul>
</div>
