<div class="p-home-pickup" id="pickup-parent-block" aria-hidden="false">

    <div class="c-section-header">
        <div class="c-section-header-primary">
            <h2 class="c-section-header-primary__heading">ピックアップ</h2>
        </div>
    </div>



    <div id="module-wrap-pickup_shop_news-13" data-name="pickup_shop_news" data-index="13">
        <div class="c-section-header-small">
            <div class="c-section-header-small-primary">
                <h2 class="c-section-header-small-primary__heading">注目のショップニュース</h2>
            </div>
        </div>
        <div class="p-home-section-contents" data-module-block=""
            data-parent-element-id="module-wrap-pickup_shop_news-13" data-module-name="pickup_shop_news"
            data-module-index="13" data-module-pattern="wide_square" data-module-id="111">
            <div class="borderbox--1JezY9_O">
                <div class="section--1WBRdOlM" style=""><a href="https://zozo.jp/search/?p_tpcsid=1549284"
                        target="_self" class="c-media fade-enter-active--37EO7EZT">
                        <div class="c-media-header --rounded --shadow"><span
                                class="wrap--507AmmEt intrinsicRate--1qjEBHfv" style="padding-top: 100%;"><img
                                    src="https://o.imgz.jp/shoptopics/1809/1549284.jpg"
                                    alt="devirock（デビロック）のショップニュース「大人気ルームウェア！フリース素材の新作も登場♪」"
                                    class="image--3YuvSMye fade-enter-active--37EO7EZT"></span></div>
                        <div class="c-media-body">
                            <p class="c-media-body__heading">大人気ルームウェア！フリース素材の新作も登場♪</p>
                            <p class="c-media-body__appendix">devirock</p>
                        </div>
                    </a></div>
            </div>
        </div>
    </div>

    <div id="module-wrap-pickup_fashion_news-15" data-name="pickup_fashion_news" data-index="15">
        <div class="c-section-header-small">
            <div class="c-section-header-small-primary">
                <h2 class="c-section-header-small-primary__heading">注目のファッションまとめ</h2>
            </div>
        </div>
        <div class="p-home-section-contents" data-module-block=""
            data-parent-element-id="module-wrap-pickup_fashion_news-15" data-module-name="pickup_fashion_news"
            data-module-index="15" data-module-pattern="wide_square" data-module-id="111">
            <div class="borderbox--1JezY9_O">
                <div class="section--1WBRdOlM" style=""><a href="https://zozo.jp/fashionnews/fineboys/114357/"
                        target="_self" class="c-media fade-enter-active--37EO7EZT">
                        <div class="c-media-header --rounded --shadow"><span
                                class="wrap--507AmmEt intrinsicRate--1qjEBHfv" style="padding-top: 100%;"><img
                                    src="https://o.imgz.jp/fashionnews/114357/master_640_1.jpg"
                                    alt="FINEBOYS（ファインボーイズ）のファッションまとめ「ザ・ノース・フェイスetc.「黒スウェット」が結局一番カッコいい！」"
                                    class="image--3YuvSMye fade-enter-active--37EO7EZT"></span></div>
                        <div class="c-media-body">
                            <p class="c-media-body__heading">ザ・ノース・フェイスetc.「黒スウェット」が結局一番カッコいい！</p>
                            <p class="c-media-body__appendix">FINEBOYS</p>
                        </div>
                    </a></div>
            </div>
        </div>
    </div>

</div>
