<div class="p-home-recruit">
    <section class="menuBox section">
        <h2>採用情報</h2>
        <div class="recruitBanner">


            <ul class="bannerPickup">
                <li class="bannerPickupItem">
                    <a class="bannerPickupLink" href="https://hrmos.co/pages/zozotech/jobs/0000204" target="_blank"
                        rel="noopener noreferrer">
                        <img src="https://o.imgz.jp/pc/default_2015/recruit/20211001_newgraduate.jpg" width="174"
                            height="88" alt="ZOZO 2023年卒 新卒エンジニア募集中">
                    </a>
                </li>
            </ul>


            <ul class="bannerRecriut">

                <li class="bannerRecriutItem">
                    <a class="bannerRecriutLink" href="https://corp.zozo.com/recruit/recruit-zozo/hr-staff/"
                        target="_blank" rel="noopener noreferrer">
                        <span class="c-badge-icon--new"></span>
                        <p class="bannerRecruitKind">人自スタッフ</p>
                        <p class="bannerRecruitScope">ZOZO</p>
                    </a>
                </li>

                <li class="bannerRecriutItem">
                    <a class="bannerRecriutLink" href="https://corp.zozo.com/recruit/recruit-zozo/villa_buyer/"
                        target="_blank" rel="noopener noreferrer">
                        <span class="c-badge-icon--new"></span>
                        <p class="bannerRecruitKind">【ZOZOVILLA】バイヤー/MD</p>
                        <p class="bannerRecruitScope">ZOZOTOWN</p>
                    </a>
                </li>

                <li class="bannerRecriutItem">
                    <a class="bannerRecriutLink" href="https://corp.zozo.com/recruit/recruit-zozo/measurement_project/"
                        target="_blank" rel="noopener noreferrer">
                        <span class="c-badge-icon--new"></span>
                        <p class="bannerRecruitKind">新規事業運営スタッフ<br><span class="bannerRecruitScope"
                                style="color:#fa1169;">※未経験歓迎！</span></p>
                        <p class="bannerRecruitScope">ZOZOSUIT・ZOZOMAT</p>
                    </a>
                </li>


                <li class="bannerRecriutItem">
                    <a class="bannerRecriutLink" href="https://corp.zozo.com/recruit/mid-career/" target="_blank"
                        rel="noopener noreferrer">
                        <p class="bannerRecruitKind">中途エンジニア・デザイナー</p>
                        <p class="bannerRecruitScope">ZOZOTOWN・WEAR</p>
                    </a>
                </li>


                <li class="bannerRecriutItem">
                    <a class="bannerRecriutLink" href="https://corp.zozo.com/recruit/handicapped/logisticstsukuba/"
                        target="_blank" rel="noopener noreferrer">
                        <p class="bannerRecruitKind">【障がい者採用】<br>労務事務・商品管理スタッフ</p>
                        <p class="bannerRecruitScope">ZOZOTOWN</p>
                    </a>
                </li>

                <li class="bannerRecriutItem karte-embed" id="karte-recruit-banner-01"></li>

            </ul>
        </div>
        <p class="more">
            <a href="https://corp.zozo.com/recruit/" target="_blank" rel="noopener noreferrer">採用情報一覧</a>
        </p>
    </section>

</div>
