<ul>
    <li><a class="sssssss" href="<?php echo $this->getData('link_facebook'); ?>"><i class="fab fa-facebook-square"></i> Facebook</a></li>
    <li><a class="sssssss" href="<?php echo $this->getData('link_twitter'); ?>"><i class="fab fa-twitter"></i> Twitter</a></li>
    <li><a class="sssssss" href="<?php echo $this->getData('link_instagram'); ?>"><i class="fab fa-instagram"></i> Instagram</a></li>
</ul>
