<ul class="s-footer-sitemap-list">
    <li><a href="/?p_no=1" target="_self">ZOZOTOWN</a></li>
    <li><a href="/shoes/?p_no=1" target="_self">ZOZOSHOES</a></li>
    <li><a href="/cosme/?p_no=1" target="_self">ZOZOCOSME</a></li>
    <li><a href="/zozogolf/?p_no=1" target="_self">ZOZOGOLF</a></li>
    <li><a href="/zozoused/" target="_self">ZOZOUSED</a></li>
    <li><a href="/zozovilla/?p_no=1" target="_self">ZOZOVILLA</a></li>
    <li><a href="/yourbrandproject/?p_no=1" target="_self">YOUR BRAND PROJECT</a></li>
</ul>
