<div class="dropdown-test">
    <i class="fas fa-bars"></i>

    <div class="dropdown-test-content">

        <div class="s-header-dropdown-column__col--search">
            <div class="s-header-dropdown-heading">アイテムを探す</div>
            <div class="s-header-dropdown-list">
                <ul>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/category/">カテゴリーから探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/brand/">ブランドから探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/shop/">公式ショップから探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/ranking/all-sales.html">ランキングから探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/sale/">セール対象から探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/coupon/">クーポン対象から探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/coordinate/">コーディネートから探す</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/detail/">こだわり条件から探す</a></li>
                </ul>
            </div>
        </div>
        <div class="s-header-dropdown-column__col--service">
            <div class="s-header-dropdown-heading">ニュース</div>
            <div class="s-header-dropdown-list">
                <ul>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/topics/">ショップニュース</a>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/fashionnews/">ファッションまとめ</a>
                </ul>
            </div>
            <div class="s-header-dropdown-heading">サービス</div>
            <div class="s-header-dropdown-list">
                <ul>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/zozoglass/">ZOZOGLASS</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/zozomat/">ZOZOMAT</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/_card/">ZOZOCARD</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/multisize/">マルチサイズ</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/giftwrapping/">ギフトラッピング</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/_member/tradein/">いつでも買い替え割</a></li>
                </ul>
            </div>
        </div>
        <div class="s-header-dropdown-column__col--mall">
            <div class="s-header-dropdown-heading">モール・ゾーン</div>
            <div class="s-header-dropdown-list">
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/"></li>
                ZOZOTOWN
                <span class="s-header-dropdown-list__item-sub">
                    日本最大級のファッション通販サイト
                </span>
                </a>
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/shoes/"></li>
                ZOZOSHOES
                <span class="s-header-dropdown-list__item-sub">
                    シューズ専門モール
                </span>
                </a>
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/cosme/"></li>
                ZOZOCOSME
                <span class="s-header-dropdown-list__item-sub">
                    コスメ専門モール
                </span>
                </a>
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/zozogolf/"></li>
                ZOZOGOLF
                <span class="s-header-dropdown-list__item-sub">
                    ゴルフ専門ゾーン
                </span>
                </a>
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/shop/zozoused/"></li>
                ZOZOUSED
                <span class="s-header-dropdown-list__item-sub">
                    ブランド古着ゾーン
                </span>
                </a>
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/zozovilla/"></li>
                ZOZOVILLA
                <span class="s-header-dropdown-list__item-sub">
                    ラグジュアリー&amp;デザイナーズゾーン
                </span>
                </a>
                <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/yourbrandproject/"></li>
                YOUR BRAND PROJECT
                <span class="s-header-dropdown-list__item-sub">
                    インフルエンサーブランドゾーン
                </span>
                </a>
            </div>
        </div>
        <div class="s-header-dropdown-column__col--other">
            <div class="s-header-dropdown-heading">ヘルプ・その他</div>
            <div class="s-header-dropdown-list">
                <ul>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/_help/">よくある質問</a></li>
                    <li><a class="s-header-dropdown-list__item" href="https://zozo.jp/welcome/">はじめての方へ</a></li>
                    <li><a class="s-header-dropdown-list__item" href="/zozo.jp/_member/regist/?pattern=4">新規会員登録</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>